
---
name: Deploy with surge

on:
  push:
    branches: [ main ]


jobs:
  build:
    name: Job_Deploy_Surge
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2-beta
        with:
          node-version: '12'

      # Runs a set of commands using the runners shell
      - name: Setup Surge
        run: npm install --global surge
      - name: Execute Deployment with Surge
        run: surge ./ ceaseless-front.surge.sh --token ${{ secrets.SURGE_TOKEN }}
        
...